# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppregpanelmixMLE <- function(ys, xs, zs, alpha0s, mu0s, sigma0s, beta0s, gamma0s, m, q, p, t) {
    .Call('normalRegPanelMix_cppregpanelmixMLE', PACKAGE = 'normalRegPanelMix', ys, xs, zs, alpha0s, mu0s, sigma0s, beta0s, gamma0s, m, q, p, t)
}

cppnormalpanelmixPMLE <- function(bs, ys, zs, mu0s, sigma0s, m, p, t, an, maxit = 2000L, ninits = 10L, tol = 1e-8, tau = 0.5, h = 0L, k = 0L, update_alpha = 1L) {
    .Call('normalRegPanelMix_cppnormalpanelmixPMLE', PACKAGE = 'normalRegPanelMix', bs, ys, zs, mu0s, sigma0s, m, p, t, an, maxit, ninits, tol, tau, h, k, update_alpha)
}

cppRegmixPMLE <- function(bs, ys, xs, zs, mu0s, sigma0s, m, p, an, maxit = 2000L, ninits = 10L, tol = 1e-8, tau = 0.5, h = 0L, k = 0L, update_alpha = 1L) {
    .Call('normalRegPanelMix_cppRegmixPMLE', PACKAGE = 'normalRegPanelMix', bs, ys, xs, zs, mu0s, sigma0s, m, p, an, maxit, ninits, tol, tau, h, k, update_alpha)
}

cppRegPanelmixPMLE <- function(bs, ys, xs, zs, mu0s, sigma0s, m, p, t, an, maxit = 2000L, ninits = 10L, tol = 1e-8, tau = 0.5, h = 0L, k = 0L, update_alpha = 1L) {
    .Call('normalRegPanelMix_cppRegPanelmixPMLE', PACKAGE = 'normalRegPanelMix', bs, ys, xs, zs, mu0s, sigma0s, m, p, t, an, maxit, ninits, tol, tau, h, k, update_alpha)
}

rcpparma_hello_world <- function() {
    .Call('normalRegPanelMix_rcpparma_hello_world', PACKAGE = 'normalRegPanelMix')
}

rcpparma_outerproduct <- function(x) {
    .Call('normalRegPanelMix_rcpparma_outerproduct', PACKAGE = 'normalRegPanelMix', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('normalRegPanelMix_rcpparma_innerproduct', PACKAGE = 'normalRegPanelMix', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('normalRegPanelMix_rcpparma_bothproducts', PACKAGE = 'normalRegPanelMix', x)
}

